version: '3.9'

services:
  redis_mailer:
    container_name: redis_mailer
    image: redis:alpine
    volumes:
      - ./redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/etc/sysctl.conf:/usr/local/etc/redis/sysctl.conf
      - ./redis/data:/data
    ports:
      - "6379:6379"
  discord_mailer:
    build: .
    container_name: discord_mailer-${VERSION}
    image: discord_mailer:${VERSION}
    environment:
      REDIS_DB: redis://redis_mailer:6379/0
    env_file:
      - ./.env
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
